- name: Create an ec2 instance
  hosts: localhost
  connection: local
  become: Flase
  gather_facts: False
  vars:
    keypair: 
    instance_type: m1.small
    security_group: my_securitygroup
    name:
    image: my_ami_id
    region: us-west-2
    zone: us-west-2a
    count: 1
    subnet_id: subnet-07d10bc0dda0bbfc6
  
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         #group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         zone: "{{ zone }}"
         vpc_subnet_id: "{{ subnet_id }}"
         assign_public_ip: yes
         instance_tags:
           Tower: RHEL
           Name: {{" name "}}
         count_tag:
           Name: web
         exact_count: "{{ count }}"
      register: ec2
